# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Bot Detector application

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
 build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-pip python3-venv
        python3 -m pip install --upgrade pip
        pip3 install flake8 pytest wheel flaskr-1.0.0-py3-none-any.whl
        
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
        
 deploy:
    runs-on: self-hosted
    needs: [build]
    steps:
      - name: create venv
        run: |
          rm -rf venv
          python3 -m venv venv
          source venv/bin/activate
          if [ -f requirements.txt ]; then pip3 install -r requirements.txt; fi
          
 Start-server:
    runs-on: self-hosted
    needs: [deploy]
    steps:
      - name: Start-server
        run: |
          source venv/bin/activate
          cd /home/runner/_work/Bot-Detector-Server-Files/Bot-Detector-Server-Files
          gunicorn --bind 0.0.0.0:5000 -w 3 -t 60 flaskweb:app
  
